server {
    listen 80;
    charset utf-8;
    # 1. Frontend Estático
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # 2. Reverse Proxy hacia el Backend
    # Fíjate: usamos "http://backend:8000". ¡Nombre del servicio Docker!
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
